matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    language: node_js
    node_js:
    - '6'
    deploy:
      provider: releases
      api_key:
        secure: DHzFJ9JGNAdeTfTmr2vLJFajTL0XHEYG1OKeD4DQhxB1mGDVLF2FX2T0PrRoqD1S084acnEKN1nElMn/NWc6eNPVksqQlC+8kVtYsX6EMOoiT8YnsQW7TbAsBEp30a/cuNWLfUFEmwsXN6zQQMgyF5vBoMjsycxDXq9MF5AQ9Y5BXM0Dky/v5fBmKyoVl76G/L6RkXM4SaTpthwfFmYlrAC9ctbCgA337qS3SmNLjh/EzdvgAkI9mKxewBizp1/T8hzagcOXs+UoDm/avhbZTTxfxf03PcBHs6/YwlVGKWnsIKD+BP0N7kt4q7QjXmetx5UDvKiYk269lyapqgJgF9QhODjuxufK8HD9dkOfDsG2kC0VR0BK7fHgkFCEItp6rvWwvvSDKVJN7ogT9V8XzQjeYTWwc03B58zu0f9hS4x5OMrZrs3z+NsZ/Qr+yaEjmJAiazkJPOpfPyQB0EllnPY+uugzo9iUMLmK99aYTgK0ZKOOHtJh0ziv6aQgKK6L8i9k7A4t99SfLlaKPCNITx4FH8TbLts6Oxm87iNhTQPafpOZUGUeuHtJywK1Rj+CfYffqIpZahG8jRkfllqMoLZ0QmBXE+CD7aPkTN3MF1Tj38Dbe3HjOGl8oJfS2VKH8dH6p6e9BBTXvU/bOKNCb8FBjNT2SY8UYAxnlDmzJDA=
      file:
        - "$TRAVIS_BUILD_DIR/releases/rocketchat-$TRAVIS_TAG-linux-x64.deb"
        - "$TRAVIS_BUILD_DIR/releases/rocketchat-$TRAVIS_TAG-linux.x86_64.rpm"
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
  - os: osx
    osx_image: xcode7.3.1
    language: generic
    node_js:
    - '6'
    before_script:
      - echo $CERTIFICATE_OSX_P12_DEVELOPER_ID_APPLICATION | base64 --decode > CERTIFICATE_OSX_P12_DEVELOPER_ID_APPLICATION.p12
      - security create-keychain -p KEYCHAIN_PASSWORD build.keychain
      - security default-keychain -s build.keychain
      - security unlock-keychain -p KEYCHAIN_PASSWORD build.keychain
      - security import CERTIFICATE_OSX_P12_DEVELOPER_ID_APPLICATION.p12 -k build.keychain -T /usr/bin/codesign
      - security find-identity -v
    deploy:
      provider: releases
      api_key:
        secure: DHzFJ9JGNAdeTfTmr2vLJFajTL0XHEYG1OKeD4DQhxB1mGDVLF2FX2T0PrRoqD1S084acnEKN1nElMn/NWc6eNPVksqQlC+8kVtYsX6EMOoiT8YnsQW7TbAsBEp30a/cuNWLfUFEmwsXN6zQQMgyF5vBoMjsycxDXq9MF5AQ9Y5BXM0Dky/v5fBmKyoVl76G/L6RkXM4SaTpthwfFmYlrAC9ctbCgA337qS3SmNLjh/EzdvgAkI9mKxewBizp1/T8hzagcOXs+UoDm/avhbZTTxfxf03PcBHs6/YwlVGKWnsIKD+BP0N7kt4q7QjXmetx5UDvKiYk269lyapqgJgF9QhODjuxufK8HD9dkOfDsG2kC0VR0BK7fHgkFCEItp6rvWwvvSDKVJN7ogT9V8XzQjeYTWwc03B58zu0f9hS4x5OMrZrs3z+NsZ/Qr+yaEjmJAiazkJPOpfPyQB0EllnPY+uugzo9iUMLmK99aYTgK0ZKOOHtJh0ziv6aQgKK6L8i9k7A4t99SfLlaKPCNITx4FH8TbLts6Oxm87iNhTQPafpOZUGUeuHtJywK1Rj+CfYffqIpZahG8jRkfllqMoLZ0QmBXE+CD7aPkTN3MF1Tj38Dbe3HjOGl8oJfS2VKH8dH6p6e9BBTXvU/bOKNCb8FBjNT2SY8UYAxnlDmzJDA=
      file:
        - "$TRAVIS_BUILD_DIR/releases/rocketchat-$TRAVIS_TAG-darwin-x64.dmg"
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
branches:
  only:
  - develop
  - master
  - travis
  - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
git:
  depth: 1
addons:
  apt:
    packages:
    - rpm
before_script:
- rm -rf releases
- travis_retry npm install
- |
  perl -pe "s/(\"version\": )\"([0-9.]+)\"/ q{\"version\": \"$TRAVIS_TAG\"} /ge" -i app/package.json
- |
  perl -pe "s/(\"build\": )\"([0-9.]+)\"/ q{\"build\": \"$TRAVIS_BUILD_NUMBER\"} /ge" -i app/package.json
script:
- npm run release
- ls releases/

