os:
  - linux
  - osx

# branches:
#   only:
#     - master

addons:
  apt:
    packages:
    - rpm
    - gcc-5
    - g++-5

env:
  - NODE_VERSION="6"

before_script:
 - chmod +x ./scripts/travis-build.sh

script: ./scripts/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
