matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    language: node_js
    node_js:
    - '6'
    services:
    - docker
    script:
    - docker run --rm -ti -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.electron:/root/.electron electronuserland/electron-builder
    - npm install
    - npm prune
    - npm run release -- --ia32

    # Install dependencies for snaps
    # before_install:
    # - sudo add-apt-repository -y ppa:snappy-dev/tools
    # - sudo apt-get -qq update
    # - sudo apt-get install -y rpm g++-multilib snapcraft
  - os: osx
    osx_image: xcode7.3.1
    language: generic
    node_js:
    - '6'
    before_script:
    - chmod +x ./scripts/travis-build.sh
    script: ./scripts/travis-build.sh

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
    - rpm
    - g++-multilib
    # - libx11-dev:i386
    # - libxext-dev:i386
    # - libxss-dev:i386

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
