matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: node_js
    - os: osx
      osx_image: xcode7.3.1
      language: node_js

branches:
  only:
  - develop
  - master
  - travis
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"

git:
  depth: 1

node_js:
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libnss3-dev
    - pkg-config

before_script:
- rm -rf releases
- travis_retry npm install

script:
- npm run release

env:
  global:
  - CXX=g++-4.8
