matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: node_js
      node_js:
      - '6'
    - os: osx
      osx_image: xcode7.3.1
      language: generic
      node_js:
      - '6'

branches:
  only:
  - develop
  - master
  - travis
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"

git:
  depth: 1

addons:
  apt:
    packages:
    - rpm

before_script:
- rm -rf releases
- travis_retry npm install

script:
- npm run release
