language: node_js

os:
  - linux
  - osx

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode7.2

services:
- docker
- mongodb

branches:
  only:
  - develop
  - master
  - "/^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"

git:
  depth: 1

node_js:
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
- rm -rf releases
- travis_retry npm install

script:
- npm run release

env:
  global:
  - CXX=g++-4.8
