# build: off

os: unstable
platform: x64

environment:
  nodejs_version: "6.3.0"
  GH_TOKEN_TEST2: "test 2"
  # matrix:
  #   - platform: x86
  #     GH_TOKEN_TEST3: "test 3"
  #     GH_TOKEN:
  #       secure: rqUx+ZsMc/HqozfHhXVgjG9rd0Iqyg+cVNakbk7EXXEsQvYC/E77jMgJutWlbI6V
  #   - platform: x64
  #     GH_TOKEN_TEST3: "test 3"
  #     GH_TOKEN:
  #       secure: rqUx+ZsMc/HqozfHhXVgjG9rd0Iqyg+cVNakbk7EXXEsQvYC/E77jMgJutWlbI6V

branches:
  only:
    - master
    - develop

skip_tags: true

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  # - .\node_modules\.bin\npm test
  # - .\node_modules\.bin\npm run e2e

build_script:
  - echo %GH_TOKEN_TEST%
  - echo %GH_TOKEN_TEST2%
  - .\node_modules\.bin\npm run release

artifacts:
  - path: 'dist\**\*.exe'
