platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

environment:
  TEST_FILES: BuildTest,extraMetadataTest,filesTest,globTest,nsisUpdaterTest

install:
  - ps: Install-Product node 6 x64
  - choco install nsis -version 3.01.0.20160420
  - dir "C:/Program Files (x86)/NSIS"
  - SET PATH=C:/Program Files (x86)/NSIS;%PATH%
  - echo "%PATH%"
  - npm install npm
  - .\node_modules\.bin\npm install

build_script:
  - npm run release
