# build: off

os: unstable

environment:
  global:
    GH_TOKEN:
      secure: rqUx+ZsMc/HqozfHhXVgjG9rd0Iqyg+cVNakbk7EXXEsQvYC/E77jMgJutWlbI6V

platform:
  - x86
  - x64

branches:
  only:
    - master
    - develop

skip_tags: true

environment:
  nodejs_version: "6.3.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  # - .\node_modules\.bin\npm test
  # - .\node_modules\.bin\npm run e2e

build_script:
  - .\node_modules\.bin\npm run release

artifacts:
  - path: 'dist\**\*.exe'
