platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6 x64
  - choco install nsis -version 3.01.0.20160420
  - SET PATH=C:/Program Files (x86)/NSIS;%PATH%
  - npm install npm
  - .\node_modules\.bin\npm install

build_script:
  - npm run release

artifacts:
  - path: 'releases\*.exe'

deploy:
  - provider: GitHub
    artifact: /.*\.exe/
    auth_token:
      secure: rqUx+ZsMc/HqozfHhXVgjG9rd0Iqyg+cVNakbk7EXXEsQvYC/E77jMgJutWlbI6V
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only

test: off
